language: ruby
rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile: server/Gemfile
install:
  - bundle install
script:
  - bundle exec rake test
notifications:
  email:
    - aaron.fischer@marbis.net
